Charts: Tighten validations Closes https://github.com/grafana/tanka/issues/691 which is mostly a failure of error messages imo
Instead of getting a `no such file`, the error is now: ```
$ tk tool charts add https://helm.releases.hashicorp.com/vault@0.19.0
Adding 1 Charts ...
 Skipping https://helm.releases.hashicorp.com/vault@0.19.0: not of form 'repo/chart@version(:path)' where repo contains no special characters.
Error: 1 Chart(s) were skipped. Please check above logs for details
```

Also, adding an invalid repo now prints out a relevant error message instead of failing in helm commands
```
$ tk tool charts add-repo https://helm.releases.hashicorp.com  https://helm.releases.hashicorp.com
 Skipping https://helm.releases.hashicorp.com: invalid name. cannot contain any special characters.
Error: 1 Repo(s) were skipped. Please check above logs for details
```