Charts: Check for output dir conflicts Closes https://github.com/grafana/tanka/issues/508
Whenever two charts will end up in the same dir, tanka will exit before doing anything

Ex, these two versions would end up in the flagger dir:
```yaml
directory: charts
repositories:
- name: flagger
  url: https://flagger.app
requires:
- chart: flagger/flagger
  version: 1.16.1
- chart: flagger/flagger
  version: 1.17.0
version: 1
```

```console
$ tk tool charts vendor
Error: Output directory conflicts found:
 - output directory "flagger" is used twice, by charts "flagger/flagger@1.16.1" and "flagger/flagger@1.17.0"
```

It checks in both `add` and `vendor` commands to handle the case where someone writes their YAML manually