Allow partial matches in the --name option (#613)
* Allow partial matches in the `--name` option

Say I get this output:
```
$ tk diff tanka/environments/my-project
Error: found multiple Environments in 'tanka/environments/my-project':
 - environments/my-project/dev
 - environments/my-project/prod
 ```

 I can now rerun this command with `--name dev` or `--name ops` instead of the whole environment name
When more than one environment matches, the same message as before is given

* Add test case

* Use std.member instead of std.findSubstr

* Add doc about --name partial matches